site_name: HEART 2020 at PC²
site_description: "HEART 2020"

nav:
        - Home: index.md
        - Program: program.md
        - Keynote Speakers: keyspeaker.md
        - Workshop: workshop.md
        - Contact: contact.md
        - Site notice: impressum.md  


theme:
        custom_dir: 'theme/'
        name: 'material'
        font: false
        favicon: 'img/favicon.ico'
        logo: 'img/pc2-logo.png'
        language: 'en'
        palette:
                primary: 'deep purple'
                accent: 'cyan'
plugins: []

