site_name: HEART 2020 at PC²
site_description: "HEART 2020"

nav:
        - Home: index.md
        - Call for Papers: cfp.md
        - Committees: committee.md
        - Submission: submission.md
        - Program: program.md
        - Keynote Speakers: keyspeaker.md
        - Workshop: workshop.md
        - Paderborn University: infos_upb.md
        - Paderborn: infos_pb.md
        - Venue: venue.md
        - Accommodation: accommodation.md
        - Travel: travel.md
        - Contact: contact.md
        - Site notice: impressum.md  


theme:
        name: null
        custom_dir: material
        feature:
                tabs: false
        favicon: 'img/favicon.ico'
        logo: 'img/pc2-logo.png'
        language: en
        font:
                text: Roboto
                code: Roboto Mono
        palette:
                primary: upbprimary
                accent: upbaccent
plugins: []
markdown_extensions: []
 


