site_name: HEART 2020 at PC²
site_description: "HEART 2020"

nav:
        - Home: index.md
        - Table-Test: tabletest.md

theme:
        name: null
        custom_dir: material
        feature:
                tabs: false
        favicon: 'img/HEART-Logo_square_orange.ico'
        logo: 'img/HEART-Logo_square.png'
        language: en
        font:
                text: Roboto
                code: Roboto Mono
        palette:
                primary: upbprimary
                accent: upbaccent
plugins: []
markdown_extensions: []
remote_branch: master


